In [1]:
import datetime as dt
from lxml import html
from bs4 import BeautifulSoup
import urllib
import sys
import requests
import operator
from datetime import timedelta
import csv
import pandas as pd
import numpy as np
import math

In [2]:
year1415 = pd.read_csv('GamesData/season1415.csv', parse_dates=['Date'])
year1516 = pd.read_csv('GamesData/season1516.csv', parse_dates=['Date'])
year1617 = pd.read_csv('GamesData/season1617.csv', parse_dates=['Date'])
year1718 = pd.read_csv('GamesData/season1718.csv', parse_dates=['Date'])
year1819 = pd.read_csv('GamesData/season1819.csv', parse_dates=['Date'])
year1920 = pd.read_csv('GamesData/season1920.csv', parse_dates=['Date'])

In [3]:
frames = [year1617,year1718,year1819,year1920]

In [5]:
allyears = pd.concat(frames)
allyears = allyears.drop_duplicates(subset=['Date', 'Home'],keep='last')


In [6]:
allyears

Date  Win_Score  Lose_Score              Home               Away  \
0    2016-11-11         94          49              Duke             Marist   
1    2016-11-11         87          64          Kentucky  Stephen F. Austin   
2    2016-11-11        103          99            Kansas            Indiana   
3    2016-11-11         88          48         Villanova          Lafayette   
4    2016-11-11         91          77            Oregon               Army   
...         ...        ...         ...               ...                ...   
4233 2020-02-20         90          60  Coastal Carolina               Troy   
4234 2020-02-20         69          58              Utah               UCLA   
4235 2020-02-20         63          54       Stony Brook            Vermont   
4236 2020-02-20         61          51            Towson     William & Mary   
4237 2020-02-20         88          70  Youngstown State       Wright State   

      WinnerHome  KenPomRank_Away  KenPomVal_Away  BPIrank_Away  BPIval_Away  \
0              1            312.0          -13.63         305.0         -8.0   
1              1            233.0           -6.19         262.0         -5.2   
2              0             44.0           14.49          32.0         10.6   
3              1            330.0          -16.79         330.0        -10.9   
4              1            230.0           -6.04         253.0         -4.7   
...          ...              ...             ...           ...          ...   
4233           1            285.0          -10.01         305.0         -7.6   
4234           0             92.0            7.80         106.0          3.7   
4235           0             59.0           11.82          41.0          9.3   
4236           0            185.0           -1.44         189.0         -0.9   
4237           1            125.0            3.90         118.0          3.0   

      ...  d_eff_Home  ppg_Home  papg_Home  Pace_Home  Three_Par_Home  \
0     ...       91.17      80.8       70.2       69.9           0.383   
1     ...       86.87      84.9       71.5       74.3           0.316   
2     ...       89.65      83.2       71.9       71.4           0.359   
3     ...       87.45      77.2       62.7       65.6           0.433   
4     ...       88.20      78.9       65.8       68.8           0.388   
...   ...         ...       ...        ...        ...             ...   
4233  ...      102.94      78.2       76.0       74.2           0.356   
4234  ...       95.61      70.6       69.8       68.1           0.386   
4235  ...       97.10      71.2       66.7       70.5           0.427   
4236  ...      100.42      70.0       65.9       66.3           0.335   
4237  ...      105.53      73.3       71.3       68.8           0.369   

      True_Shoot_Home  Tov_Home  Opp_Three_Par_Home  Opp_True_Shoot_Home  \
0               0.588      14.2               0.288                0.510   
1               0.564      13.4               0.333                0.507   
2               0.583      15.1               0.342                0.515   
3               0.612      15.0               0.400                0.506   
4               0.582      14.7               0.378                0.494   
...               ...       ...                 ...                  ...   
4233            0.542      18.2               0.447                0.544   
4234            0.546      17.3               0.352                0.527   
4235            0.522      17.7               0.419                0.491   
4236            0.528      15.3               0.424                0.512   
4237            0.512      14.4               0.332                0.521   

      Opp_Tov_Home  
0             14.9  
1             16.9  
2             16.1  
3             17.6  
4             16.6  
...            ...  
4233          16.9  
4234          15.9  
4235          16.5  
4236          15.0  
4237          14.9  

[20914 rows x 38 columns]

In [8]:
full = allyears.dropna()

In [14]:
y = 0
for x in full.columns:
    print(x,y)
    y+=1

Date 0
Win_Score 1
Lose_Score 2
Home 3
Away 4
WinnerHome 5
KenPomRank_Away 6
KenPomVal_Away 7
BPIrank_Away 8
BPIval_Away 9
SRS_Away 10
o_eff_Away 11
d_eff_Away 12
ppg_Away 13
papg_Away 14
Pace_Away 15
Three_Par_Away 16
True_Shoot_Away 17
Tov_Away 18
Opp_Three_Par_Away 19
Opp_True_Shoot_Away 20
Opp_Tov_Away 21
KenPomRank_Home 22
KenPomVal_Home 23
BPIrank_Home 24
BPIval_Home 25
SRS_Home 26
o_eff_Home 27
d_eff_Home 28
ppg_Home 29
papg_Home 30
Pace_Home 31
Three_Par_Home 32
True_Shoot_Home 33
Tov_Home 34
Opp_Three_Par_Home 35
Opp_True_Shoot_Home 36
Opp_Tov_Home 37


In [12]:
full

Date  Win_Score  Lose_Score              Home               Away  \
0    2016-11-11         94          49              Duke             Marist   
1    2016-11-11         87          64          Kentucky  Stephen F. Austin   
2    2016-11-11        103          99            Kansas            Indiana   
3    2016-11-11         88          48         Villanova          Lafayette   
4    2016-11-11         91          77            Oregon               Army   
...         ...        ...         ...               ...                ...   
4233 2020-02-20         90          60  Coastal Carolina               Troy   
4234 2020-02-20         69          58              Utah               UCLA   
4235 2020-02-20         63          54       Stony Brook            Vermont   
4236 2020-02-20         61          51            Towson     William & Mary   
4237 2020-02-20         88          70  Youngstown State       Wright State   

      WinnerHome  KenPomRank_Away  KenPomVal_Away  BPIrank_Away  BPIval_Away  \
0              1            312.0          -13.63         305.0         -8.0   
1              1            233.0           -6.19         262.0         -5.2   
2              0             44.0           14.49          32.0         10.6   
3              1            330.0          -16.79         330.0        -10.9   
4              1            230.0           -6.04         253.0         -4.7   
...          ...              ...             ...           ...          ...   
4233           1            285.0          -10.01         305.0         -7.6   
4234           0             92.0            7.80         106.0          3.7   
4235           0             59.0           11.82          41.0          9.3   
4236           0            185.0           -1.44         189.0         -0.9   
4237           1            125.0            3.90         118.0          3.0   

      ...  d_eff_Home  ppg_Home  papg_Home  Pace_Home  Three_Par_Home  \
0     ...       91.17      80.8       70.2       69.9           0.383   
1     ...       86.87      84.9       71.5       74.3           0.316   
2     ...       89.65      83.2       71.9       71.4           0.359   
3     ...       87.45      77.2       62.7       65.6           0.433   
4     ...       88.20      78.9       65.8       68.8           0.388   
...   ...         ...       ...        ...        ...             ...   
4233  ...      102.94      78.2       76.0       74.2           0.356   
4234  ...       95.61      70.6       69.8       68.1           0.386   
4235  ...       97.10      71.2       66.7       70.5           0.427   
4236  ...      100.42      70.0       65.9       66.3           0.335   
4237  ...      105.53      73.3       71.3       68.8           0.369   

      True_Shoot_Home  Tov_Home  Opp_Three_Par_Home  Opp_True_Shoot_Home  \
0               0.588      14.2               0.288                0.510   
1               0.564      13.4               0.333                0.507   
2               0.583      15.1               0.342                0.515   
3               0.612      15.0               0.400                0.506   
4               0.582      14.7               0.378                0.494   
...               ...       ...                 ...                  ...   
4233            0.542      18.2               0.447                0.544   
4234            0.546      17.3               0.352                0.527   
4235            0.522      17.7               0.419                0.491   
4236            0.528      15.3               0.424                0.512   
4237            0.512      14.4               0.332                0.521   

      Opp_Tov_Home  
0             14.9  
1             16.9  
2             16.1  
3             17.6  
4             16.6  
...            ...  
4233          16.9  
4234          15.9  
4235          16.5  
4236          15.0  
4237          14.9  

[20171 rows x 38 columns]

In [103]:
X = full.iloc[:,[11,12,15,16,17,18,19,20,21,27,28,31,32,33,34,35,36,37]]
y = full.iloc[:,5]

In [52]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

In [121]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (15128, 18)
Training Labels Shape: (15128,)
Testing Features Shape: (5043, 18)
Testing Labels Shape: (5043,)


In [122]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred_clf=clf.predict(X_test)

In [123]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_clf))

Accuracy: 0.7325004957366646


In [124]:
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_,index=X.columns).sort_values(ascending=False)
feature_imp

o_eff_Home             0.102208
o_eff_Away             0.093412
d_eff_Home             0.089585
d_eff_Away             0.084489
Opp_True_Shoot_Home    0.059490
Opp_True_Shoot_Away    0.058673
True_Shoot_Away        0.058447
True_Shoot_Home        0.051775
Tov_Home               0.044785
Tov_Away               0.042815
Opp_Three_Par_Away     0.040138
Opp_Tov_Home           0.039428
Three_Par_Home         0.039398
Pace_Home              0.039271
Opp_Tov_Away           0.039202
Pace_Away              0.039165
Opp_Three_Par_Home     0.038927
Three_Par_Away         0.038794
dtype: float64

In [125]:
old = full[['Home','Away','WinnerHome','KenPomVal_Away','BPIval_Away','SRS_Away','KenPomVal_Home','BPIval_Home','SRS_Home']]
A = old.iloc[:,[3,4,5,6,7,8]]
b = old.iloc[:,2]
# Split the data into training and testing sets
A_train, A_test, b_train, b_test = train_test_split(A, b, test_size = 0.25, random_state = 42)

print('Training Features Shape:', A_train.shape)
print('Training Labels Shape:', b_train.shape)
print('Testing Features Shape:', A_test.shape)
print('Testing Labels Shape:', b_test.shape)

Training Features Shape: (15128, 6)
Training Labels Shape: (15128,)
Testing Features Shape: (5043, 6)
Testing Labels Shape: (5043,)


In [126]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
old_clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
old_clf.fit(A_train,b_train)

b_pred_clf=old_clf.predict(A_test)

In [127]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(b_test, b_pred_clf))

Accuracy: 0.7330953797342852


In [128]:
import pandas as pd
feature_imp = pd.Series(old_clf.feature_importances_,index=A.columns).sort_values(ascending=False)
feature_imp

KenPomVal_Away    0.188027
KenPomVal_Home    0.182008
SRS_Away          0.160763
BPIval_Away       0.159637
SRS_Home          0.157953
BPIval_Home       0.151612
dtype: float64

In [129]:
ISUatKU = [110.9,95.44,71,.381,.538,15.9,.377,.535,18.1,118.14,80.41,68.6,.332,.568,16.2,.414,.462,17.1]
isuATku = [10.8,6.3,10.51,31.01,18.4,25.79]
game = [ISUatKU]
game2= [isuATku]

In [130]:
y_pred_clf=clf.predict(game)
y_pred_old_clf=old_clf.predict(game2)

In [131]:
y_pred_clf

array([1], dtype=int64)

In [132]:
y_pred_old_clf

array([1], dtype=int64)

In [133]:
clf.predict_proba(game)

array([[0.14, 0.86]])

In [135]:
old_clf.predict_proba(game2)

array([[0.05, 0.95]])