In [2]:
import datetime as dt
from lxml import html
from bs4 import BeautifulSoup
import urllib
import sys
import requests
import operator
from datetime import timedelta
import csv
import pandas as pd
import numpy as np
import math

In [3]:
year1617 = pd.read_csv('season1617.csv', parse_dates=['Date'])
year1718 = pd.read_csv('season1718.csv', parse_dates=['Date'])
year1819 = pd.read_csv('season1819.csv', parse_dates=['Date'])
year1920 = pd.read_csv('season1920.csv', parse_dates=['Date'])

In [4]:
frames = [year1617,year1718,year1819,year1920]

In [5]:
allyears = pd.concat(frames)
allyears = allyears.drop_duplicates(subset=['Date', 'Home'],keep='last')


In [6]:
allyears

Unnamed: 0       Date  Win_Score  Lose_Score                Home  \
0              0 2016-11-11         94          49                Duke   
1              1 2016-11-11         87          64            Kentucky   
2              2 2016-11-11        103          99              Kansas   
3              3 2016-11-11         88          48           Villanova   
4              4 2016-11-11         91          77              Oregon   
...          ...        ...        ...         ...                 ...   
5298        5298 2020-03-11         74          69  Alabama-Birmingham   
5299        5299 2020-03-11         71          69        Oregon State   
5300        5300 2020-03-11         86          73            Arkansas   
5301        5301 2020-03-11         77          70             Arizona   
5302        5302 2020-03-11         82          68            Colorado   

                   Away  WinnerHome  KenPomRank_Away  KenPomVal_Away  \
0                Marist           1            312.0          -13.63   
1     Stephen F. Austin           1            233.0           -6.19   
2               Indiana           0             44.0           14.49   
3             Lafayette           1            330.0          -16.79   
4                  Army           1            230.0           -6.04   
...                 ...         ...              ...             ...   
5298  Texas-San Antonio           1            210.0           -3.84   
5299               Utah           1            114.0            5.56   
5300         Vanderbilt           1            169.0            0.14   
5301         Washington           1             54.0           12.67   
5302   Washington State           0            127.0            4.22   

      BPIrank_Away  ...  d_eff_Home  ppg_Home  papg_Home  Pace_Home  \
0            305.0  ...       91.17      80.8       70.2       69.9   
1            262.0  ...       86.87      84.9       71.5       74.3   
2             32.0  ...       89.65      83.2       71.9       71.4   
3            330.0  ...       87.45      77.2       62.7       65.6   
4            253.0  ...       88.20      78.9       65.8       68.8   
...            ...  ...         ...       ...        ...        ...   
5298         230.0  ...       99.65      13.0       67.3       67.2   
5299         117.0  ...      111.51      13.0       71.2       66.6   
5300         165.0  ...      109.40      12.0       75.8       71.4   
5301          70.0  ...      113.66      11.0       76.4       70.3   
5302         135.0  ...      110.26      11.0       70.9       68.2   

      Three_Par_Home  True_Shoot_Home  Tov_Home  Opp_Three_Par_Home  \
0              0.383            0.588      14.2               0.288   
1              0.316            0.564      13.4               0.333   
2              0.359            0.583      15.1               0.342   
3              0.433            0.612      15.0               0.400   
4              0.388            0.582      14.7               0.378   
...              ...              ...       ...                 ...   
5298           0.300            0.537      19.0               0.409   
5299           0.349            0.559      15.3               0.364   
5300           0.399            0.553      14.4               0.333   
5301           0.347            0.546      14.5               0.377   
5302           0.386            0.544      16.8               0.321   

      Opp_True_Shoot_Home  Opp_Tov_Home  
0                   0.510          14.9  
1                   0.507          16.9  
2                   0.515          16.1  
3                   0.506          17.6  
4                   0.494          16.6  
...                   ...           ...  
5298                0.514          16.2  
5299                0.529          16.2  
5300                0.516          19.2  
5301                0.498          18.1  
5302                0.500          17.0  

[21979 rows x 41 columns]

In [7]:
full = allyears.dropna()

In [8]:
y = 0
for x in full.columns:
    print(x,y)
    y+=1

Unnamed: 0 0
Date 1
Win_Score 2
Lose_Score 3
Home 4
Away 5
WinnerHome 6
KenPomRank_Away 7
KenPomVal_Away 8
BPIrank_Away 9
BPIval_Away 10
SRS_Away 11
SOS_Away 12
o_eff_Away 13
d_eff_Away 14
ppg_Away 15
papg_Away 16
Pace_Away 17
Three_Par_Away 18
True_Shoot_Away 19
Tov_Away 20
Opp_Three_Par_Away 21
Opp_True_Shoot_Away 22
Opp_Tov_Away 23
KenPomRank_Home 24
KenPomVal_Home 25
BPIrank_Home 26
BPIval_Home 27
SRS_Home 28
SOS_Home 29
o_eff_Home 30
d_eff_Home 31
ppg_Home 32
papg_Home 33
Pace_Home 34
Three_Par_Home 35
True_Shoot_Home 36
Tov_Home 37
Opp_Three_Par_Home 38
Opp_True_Shoot_Home 39
Opp_Tov_Home 40


In [9]:
full

Unnamed: 0       Date  Win_Score  Lose_Score                Home  \
0              0 2019-11-05         69          62            Kentucky   
1              1 2019-11-05         68          66                Duke   
2              2 2019-11-05         87          74          Miami (FL)   
3              3 2019-11-05         74          59             Florida   
4              4 2019-11-05         95          71            Maryland   
...          ...        ...        ...         ...                 ...   
5298        5298 2020-03-11         74          69  Alabama-Birmingham   
5299        5299 2020-03-11         71          69        Oregon State   
5300        5300 2020-03-11         86          73            Arkansas   
5301        5301 2020-03-11         77          70             Arizona   
5302        5302 2020-03-11         82          68            Colorado   

                   Away  WinnerHome  KenPomRank_Away  KenPomVal_Away  \
0        Michigan State           1              7.0           24.03   
1                Kansas           1              1.0           30.23   
2            Louisville           0              9.0           21.36   
3         North Florida           1            166.0            0.37   
4            Holy Cross           1            344.0          -21.34   
...                 ...         ...              ...             ...   
5298  Texas-San Antonio           1            210.0           -3.84   
5299               Utah           1            114.0            5.56   
5300         Vanderbilt           1            169.0            0.14   
5301         Washington           1             54.0           12.67   
5302   Washington State           0            127.0            4.22   

      BPIrank_Away  ...  d_eff_Home  ppg_Home  papg_Home  Pace_Home  \
0              4.0  ...      113.37       6.0       74.4       68.5   
1              1.0  ...      117.58       6.0       82.5       72.9   
2              8.0  ...      107.91      16.0       71.2       68.7   
3            151.0  ...      113.49      12.0       71.9       66.3   
4            345.0  ...      114.29       7.0       71.8       67.7   
...            ...  ...         ...       ...        ...        ...   
5298         230.0  ...       99.65      13.0       67.3       67.2   
5299         117.0  ...      111.51      13.0       71.2       66.6   
5300         165.0  ...      109.40      12.0       75.8       71.4   
5301          70.0  ...      113.66      11.0       76.4       70.3   
5302         135.0  ...      110.26      11.0       70.9       68.2   

      Three_Par_Home  True_Shoot_Home  Tov_Home  Opp_Three_Par_Home  \
0              0.266            0.561      15.8               0.383   
1              0.315            0.559      15.2               0.267   
2              0.372            0.525      15.1               0.347   
3              0.368            0.555      15.5               0.356   
4              0.431            0.532      14.3               0.381   
...              ...              ...       ...                 ...   
5298           0.300            0.537      19.0               0.409   
5299           0.349            0.559      15.3               0.364   
5300           0.399            0.553      14.4               0.333   
5301           0.347            0.546      14.5               0.377   
5302           0.386            0.544      16.8               0.321   

      Opp_True_Shoot_Home  Opp_Tov_Home  
0                   0.489          15.1  
1                   0.489          17.7  
2                   0.526          15.1  
3                   0.519          16.9  
4                   0.489          15.1  
...                   ...           ...  
5298                0.514          16.2  
5299                0.529          16.2  
5300                0.516          19.2  
5301                0.498          18.1  
5302                0.500          17.0  

[5067 rows x 41 columns]

In [42]:
X = full.iloc[:,[12,17,18,19,20,21,22,23,29,34,35,36,37,38,39,40]]
y = full.iloc[:,6]

In [43]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

In [44]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (3800, 16)
Training Labels Shape: (3800,)
Testing Features Shape: (1267, 16)
Testing Labels Shape: (1267,)


In [45]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred_clf=clf.predict(X_test)

In [46]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_clf))

Accuracy: 0.7237569060773481


In [47]:
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_,index=X.columns).sort_values(ascending=False)
feature_imp

Opp_True_Shoot_Home    0.096861
Opp_True_Shoot_Away    0.095807
True_Shoot_Home        0.082142
True_Shoot_Away        0.077168
SOS_Home               0.065816
Tov_Away               0.061090
SOS_Away               0.059371
Tov_Home               0.058967
Opp_Tov_Home           0.055111
Opp_Three_Par_Home     0.053684
Three_Par_Home         0.051195
Three_Par_Away         0.048990
Opp_Tov_Away           0.048951
Pace_Away              0.048587
Pace_Home              0.048475
Opp_Three_Par_Away     0.047787
dtype: float64

In [48]:
old = full[['Home','Away','WinnerHome','KenPomVal_Away','BPIval_Away','SRS_Away','KenPomVal_Home','BPIval_Home','SRS_Home']]
A = old.iloc[:,[3,4,5,6,7,8]]
b = old.iloc[:,2]
# Split the data into training and testing sets
A_train, A_test, b_train, b_test = train_test_split(A, b, test_size = 0.25, random_state = 42)

print('Training Features Shape:', A_train.shape)
print('Training Labels Shape:', b_train.shape)
print('Testing Features Shape:', A_test.shape)
print('Testing Labels Shape:', b_test.shape)

Training Features Shape: (3800, 6)
Training Labels Shape: (3800,)
Testing Features Shape: (1267, 6)
Testing Labels Shape: (1267,)


In [49]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
old_clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
old_clf.fit(A_train,b_train)

b_pred_clf=old_clf.predict(A_test)

In [50]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(b_test, b_pred_clf))

Accuracy: 0.7150749802683505


In [51]:
import pandas as pd
feature_imp = pd.Series(old_clf.feature_importances_,index=A.columns).sort_values(ascending=False)
feature_imp

KenPomVal_Home    0.188223
BPIval_Home       0.184468
KenPomVal_Away    0.179062
BPIval_Away       0.176479
SRS_Away          0.139175
SRS_Home          0.132593
dtype: float64

In [58]:
ISUatKU = [11.63,71,.381,.538,15.9,.377,.535,18.1,10.07,68.6,.332,.568,16.2,.414,.462,17.1]
isuATku = [10.8,6.3,10.51,31.01,18.4,25.79]
game = [ISUatKU]
game2= [isuATku]

In [59]:
y_pred_clf=clf.predict(game)
y_pred_old_clf=old_clf.predict(game2)

In [60]:
y_pred_clf

array([1], dtype=int64)

In [61]:
y_pred_old_clf

array([1], dtype=int64)

In [62]:
clf.predict_proba(game)

array([[0.11, 0.89]])

In [63]:
old_clf.predict_proba(game2)

array([[0.13, 0.87]])